<img src="https://github.com/4GeeksAcademy/machine-learning-prework/blob/main/02-numpy/assets/numpy_logo.png?raw=1" alt="logo" width="400"/>

## Introduction to numpy

NumPy stands for 'Numerical Python'. It is an open-source Python library used to perform various mathematical and scientific tasks. It contains multi-dimensional arrays and matrices, along with many high-level mathematical functions that operate on these arrays and matrices. It contains among other things:

→ a powerful N-dimensional array object

→ sophisticated (broadcasting) functions

→ tools for integrating C/C++ and Fortran code

→ useful linear algebra, Fourier transform, and random number capabilities

## Installing NumPy
When you want to work with numpy locally, you should run the following commands:

You can install NumPy with:\
`pip install numpy`\
or\
`conda install numpy`

In our case, 4Geeks have prepared all the environment in order that you can work comfortably.

## Why should we use NumPy?

Numpy is a library to perform numerical calculation in python. We will use it mainly because it allows us to create and modify matrices, and to do operations on them with ease.

NumPy is, like Pandas, Matplotlib or Scikit-Learn, one of the packages that you cannot miss when you are learning Machine Learning, mainly because this library provides a matrix data structure that has some benefits over regular Python lists. Some of these benefits are: being more compact, quicker access to reading and writing articles, being more convenient and more efficient.

For example, we will see later in the bootcamp that working with images means dealing with three-dimensional matrices as large as 3840 x 2160, which means we will have 3×3840×2160 = 24883200 entries!!! 😱😱😱.

Working with matrices of that magnitude is practically impossible to carry out with lists and dictionaries if one wants to have an efficient and fast programming.

#### Exercise: Import the numpy package under the name `np` (★☆☆)

`numpy` is commonly imported as `np` so we highly recommend to put this alias.

In [3]:
!pip install numpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.9/16.9 MB 134.2 MB/s eta 0:00:0000:0100:01


In [4]:
import numpy as np

## What is an array and why it is importante for machine learning?

An array is a data structure consisting of a collection of elements (values or variables), each identified by at least one array index or key.


![alt text](assets/1D.png "1D")

We can have arrays from several dimension. Neural networks sometimes deal with 4D arrays. An array is known as the central data structure of the NumPy library. Array in NumPy is called as NumPy Array. Later, we will use also other kind of arrays thar are called: Tensors.

![alt text](./assets/3D.png "3D")

#### Exercise: Print the numpy version and the configuration (★☆☆)

You can print the version of any package of Python using `name_of_package.__version__`

In [5]:
import numpy as np
print(np.__version__)

1.22.4


In [6]:
import numpy as np

#### Exercise: Create a null vector of size 10 (★☆☆)

A `null vector` is an array of zeros (`0`), also called `inicializacion vector`.

Check de function `np.zeros` (https://numpy.org/doc/stable/reference/generated/numpy.zeros.html)

In [7]:
np.zeros(0)

array([], dtype=float64)

#### Exercise: Create a vector of ones with size 10 (★☆☆)
Check de function `np.ones` (https://numpy.org/doc/stable/reference/generated/numpy.ones.html)

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Exercise: Create an 1D array with specific start value, end value and number of values (★☆☆)

Check the function `np.linspace` (https://numpy.org/doc/stable/reference/generated/numpy.linspace.html)

In [9]:
np.linspace(1,2,10)

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

#### Run: Create a vector (1D array) with random integers from 10 to 49 and dimension 1x35 (★☆☆)

When `dimension` is expressed `1x35` it means: One dimension array with 35 items (length=35).

Check the function `np.random` which allows you to create random arrays (https://numpy.org/doc/1.16/reference/routines.random.html)

In [12]:
import numpy as np

# 10 random numbers between (0, 1)
print(np.random.random(10)) 

[0.89251882 0.99401267 0.0893251  0.18149506 0.1904414  0.14023682
 0.61715087 0.07905879 0.38343052 0.95861024]


In [15]:
## Two ways to create numbers with normal distribution
print(np.random.rand(10)) # 10 random values with distribution N(0,1)
print(np.random.normal(loc = 0, scale = 1, size = 10)) # 10 random values with distribution N(0,1)

[0.81197089 0.72810098 0.70417483 0.36836591 0.39540432 0.11838584
 0.29606222 0.66810822 0.97920539 0.68018702]
[ 2.18305113  2.05492409 -3.24794357 -0.81883485 -1.27392937  0.17495088
  7.50361464  4.22773246 -2.78640509  3.63732879]


In [ ]:
## Did you notice the difference between both functions? 
print(np.random.normal(loc = -5, scale = 33, size = 10)) # 10 random values with distribution N(-5,33)

In [ ]:
## 10 random values with uniform distribution. That is, all values have the same probability
print(np.random.uniform(-30,100,10)) # All values are between -30 and 100.

In [16]:
# 10 integers values between 0 and 100.
print(np.random.randint(0, 100, 10))

[22 27 96 83 63 93 21 21 77 20]


In [17]:
# 10 random values with Chi distribution with 5 degrees of freedom
print(np.random.chisquare(5,10))

[ 1.75555337  2.05946944 10.59340977 10.57510058  5.55862995  2.86361639
  7.01135584  1.24301743 10.71380938  5.63575798]


The above examples are the most common distribution and random values you will learn throughout the bootcamp. Now, let's deal with those arrays.

#### Exercise: Reverse one of the last vector we created before (first element becomes last) (★☆☆)
Try with `[::-1]`

#### Exercise: Create a 5x5 identidy matrix (★☆☆)
Check the function `np.eye`(https://numpy.org/devdocs/reference/generated/numpy.eye.html)

#### Exercise: Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
Check the function `where`(https://numpy.org/devdocs/reference/generated/numpy.where.html)

#### Exercise: Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
Check the function `min`(https://numpy.org/devdocs/reference/generated/numpy.where.html) and `max`(https://numpy.org/devdocs/reference/generated/numpy.max.html)

#### Exercise: Create a random vector of size 30 and find the mean value (★☆☆)

#### Exercise: Define a function with input your date of birth (yyyy/mm/dd) that returns a random array with the following dimensions: (★★☆)
$$yyyy-1900 \times |mm - dd|$$


In [85]:
!pip install pandas


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.7/11.7 MB 141.6 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 503.5/503.5 kB 122.9 MB/s eta 0:00:00


In [86]:
import datetime
import pandas as pd
x=datetime.datetime(1987,2,12)

In [92]:
def matr_nac (x=datetime.datetime(1987,2,12)):
    anio= int(x.strftime('%Y'))
    mes= int(x.strftime('%m'))
    dia = int(x.strftime('%d'))
    rand_arr= np.random.random((anio-1900, abs(mes-dia)))
    return (rand_arr)

print(matr_nac)


<function matr_nac at 0x7f6ae0289160>


## What is the difference between Python List and a Numpy Array?

- Python list can contain elements with different data types whereas Numpy Array‘s elements are always homogeneous (same data types).
- NumPy arrays are faster and more compact than Python lists.

## Why NumPy Arrays are faster than Lists?

- NumPy Array uses fixed memory to store data and less memory than Python lists.
- Contiguous memory allocation in NumPy Arrays.

#### Exercise: Convert the list `my_list = [1, 2, 3]` to numpy array (★☆☆)

#### Exercise: Convert the tuple `my_list = (1, 2, 3)` to numpy array (★☆☆)

#### Exercise: Convert the list of tuples `my_list = [(1,2,3), (4,5)]` to numpy array (★☆☆)

#### Exercise: Resize a random array of dimensions 5x12 into 12x5 (★☆☆)
Check `reshape`from `numpy`(https://numpy.org/doc/stable/reference/generated/numpy.reshape.html)

#### Exercise: Create a function that normalize a 5x5 random matrix (★☆☆)
Remember from probability (https://en.wikipedia.org/wiki/Normalization_(statistics)) that :
$$ x_{norm} = \frac{x - \bar{x}}{\sigma}$$


## Stacking numpy arrays

Stacking is used to join a sequence of same dimension arrays along a new axis.
`numpy.stack(arrays,axis)` : It returns a stacked array of the input arrays which has one more dimension than the input arrays.

### You have two ways to do it:


![alt text](./assets/stack.jpeg "stack")


### or


![alt text](./assets/stack2.jpeg "stack")




#### Exercise: Generate two random arrays with integers and apply the stacking using `stack` (★★☆)

#### Exercise: Generate two random arrays with integers and apply the stacking using `hstack` and `vstack` (★★☆)

## Basic maths in numpy

You can make typical math operations like:

- Addition,Subtraction,Multiplication and Division between two arrays using numpy.
- Operation on array using sum() & cumsum() function.
- Minimum and Maximum value from an array
- Exponent/Power , Square Root and Cube Root functions

or even apply common trigonometric functions:

- `numpy.sin()`:  Sine (x) Function
- `numpy.cos()`: Cosine(x) Function
- `numpy.tan()`: Tangent(x)Function
- `numpy.sinh()`: Hyperbolic Sine (x) Function
- `numpy.cosh()`: Hyperbolic Cosine(x) Functionv
- `numpy.tanh()`: Hyperbolic Tangent(x)Function
- `numpy.arcsin()`: Inverse Sine Function
- `numpy.arccos()`: Inverse Cosine Function
- `numpy.arctan()`: Inverse Tangent Function
- `numpy.pi`: pi value
- `numpy.hypot(w,h)`: For calculating Hypotenuse $c = \sqrt{(w^2 + h^2)}$
- `numpy.rad2deg()`: Radians to degrees
- `numpy.deg2rad()`: Degrees to radians

#### Exercise: Generate two random 8 - dimensional vectors and apply the most common operation between vectors:  addition, substraction, multiplication, division(★☆☆)

Check the math functions here: https://numpy.org/doc/stable/reference/routines.math.html

#### Exercise: Generate two random matrices with dimensions between 5 and 10, e.g. 5x7 vs 8x9 and try. Were you able to do the matrix multiplication? why? (★★☆) 

#### Exercise: Given 2 numpy arrays as matrices, output the result of multiplying the 2 matrices (as a numpy array) Were you able to do the matrix multiplication? (★★☆) 

$$ a = \left(\begin{matrix}
0 & 1 & 2\\ 
3 & 4 & 5\\ 
6 & 7 & 8
\end{matrix}\right)$$

$$ b = \left(\begin{matrix}
2 & 3 & 4\\ 
5 & 6 & 7\\ 
8 & 9 & 10
\end{matrix}\right)$$




#### Exercise: Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★★☆)

## Data types

Do you think the following preposition is true?
`8==8`

Surely you will definetely say yes, which is true mathematically, but computationally it is not always the same, at least in terms of memory. For example, run the following cell:

In [ ]:
import sys

# int64
x = np.array(123)
print("int64: " + str(sys.getsizeof(x)))

# int8
x = np.array(123,dtype=np.int8)
print("int8: " + str(sys.getsizeof(x)))

# float32
x = np.array(123,dtype=np.float32)
print("float32: " + str(sys.getsizeof(x)))

## It turns out that there are many computational representation of the same number and you can create arrays with different Data Types (dtypes) depending what you need:

- Boolean : `np.bool_`
- Char : `np.byte`
- Short : `np.short`
- Integer : `np.short`
- Long : `np.int_`
- Float : `np.single`&np.float32`
- Double :`np.double`&`np.float64`
- `np.int8`: integer (-128 to 127)
- `np.int16`:integer( -32768 to 32767)
- `np.int32`: integer(-2147483648 to 2147483647)
- `np.int64`:integer( -9223372036854775808 to 9223372036854775807)


Sometimes, you will need to load, create or export arrays from different data types.


## Harder exercises

The next exercises are related with real situations you could face while you are working in data science and machine learning and we will be frequently talking about matrices and bidimensional arrays.

#### Exercise: Subtract the mean of each row of a matrix (★★☆)

In [35]:
matriz = np.random.randint(5, size=(3,3))
print(matriz)
print()
media_matriz = matriz.mean(axis=1, keepdims= True)
resultado = matriz-media_matriz
print(media_matriz)
print()
print(resultado)

[[3 2 1]
 [1 3 2]
 [3 1 1]]

[[2.        ]
 [2.        ]
 [1.66666667]]

[[ 1.          0.         -1.        ]
 [-1.          1.          0.        ]
 [ 1.33333333 -0.66666667 -0.66666667]]


#### Exercise: How to get the dates of yesterday, today and tomorrow? (★★☆)
Check `np.datetime64`, `np.timedelta64` in numpy (https://numpy.org/doc/stable/reference/arrays.datetime.html)

In [43]:
hoy = np.datetime64('today', 'M')
hoy - np.timedelta64(4,'Y')

numpy.datetime64('2018-05')

#### Exercise: How to get all the dates corresponding to the month of December 2022? (★★☆)
Combine `arange`with `datetime`


In [45]:
np.arange('2022-12', '2023-01', dtype= 'datetime64[h]') # datetime64[D] imprime por día el rango

array(['2022-12-01T00', '2022-12-01T01', '2022-12-01T02', '2022-12-01T03',
       '2022-12-01T04', '2022-12-01T05', '2022-12-01T06', '2022-12-01T07',
       '2022-12-01T08', '2022-12-01T09', '2022-12-01T10', '2022-12-01T11',
       '2022-12-01T12', '2022-12-01T13', '2022-12-01T14', '2022-12-01T15',
       '2022-12-01T16', '2022-12-01T17', '2022-12-01T18', '2022-12-01T19',
       '2022-12-01T20', '2022-12-01T21', '2022-12-01T22', '2022-12-01T23',
       '2022-12-02T00', '2022-12-02T01', '2022-12-02T02', '2022-12-02T03',
       '2022-12-02T04', '2022-12-02T05', '2022-12-02T06', '2022-12-02T07',
       '2022-12-02T08', '2022-12-02T09', '2022-12-02T10', '2022-12-02T11',
       '2022-12-02T12', '2022-12-02T13', '2022-12-02T14', '2022-12-02T15',
       '2022-12-02T16', '2022-12-02T17', '2022-12-02T18', '2022-12-02T19',
       '2022-12-02T20', '2022-12-02T21', '2022-12-02T22', '2022-12-02T23',
       '2022-12-03T00', '2022-12-03T01', '2022-12-03T02', '2022-12-03T03',
       '2022-12-03T04', '

#### Exercise: Extract the integer part of a random array of positive numbers using 2 different methods (★★☆)

In [67]:
parte_entera = np.random.uniform(1,5,10)
np.floor(parte_entera) # extraer la parte entera
parte_entera.astype(int) #otra forma
parte_entera//1 # otra
np.trunc(parte_entera) # otra

array([1., 3., 4., 1., 3., 1., 2., 2., 2., 3.])

#### Exercise: Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [78]:
np.tile(np.arange(0,5), (5,1)) # hacer una matriz

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [95]:
x = np.zeros((5,5))
x += np.arange(5)
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### Exercise: Consider a generator function that generates 10 integers and use it to build an array (★★☆)

In [101]:
def generate(): # funciones generadoras estan pensadas para ser iterables, no guardan valores en memoria. 
    for x in range(10):
        yield x # yield
Z = np.fromiter(generate(),dtype=int, count=-1) # formiter crea un array iterable, count=-1 (por default) cunatas veces lo itera
print(Z)

[0 1 2 3 4 5 6 7 8 9]


#### Exercise: Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### Exercise: Create a random vector of size 10 and sort it (★★☆)

#### Exercise: Consider two random array A and B, check if they are equal (★★☆)

#### Exercise: Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★★)
Suggestion: check how to calculate the "square of a matrix"

#### Exercise: Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### Exercise: How to print all the values of an array? (★★☆)

#### Exercise: How to convert a float (32 bits) array into an integer (32 bits) in place?
Check https://stackoverflow.com/a/4396247/5989906

#### Exercise: Subtract the mean of each row of a matrix (★★☆)

#### Exercise: How to sort an array by the nth column? (★★☆)

#### Exercise: Find the position of a the minimum of a 2D matrix? (★★☆)

#### Exercise: Read an image using openCV, check its dimensions, normalize the numbers and show the image (★★★)
Check: https://www.geeksforgeeks.org/python-opencv-cv2-imread-method/

#### Exercise: Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### Exercise: How to get the diagonal of a dot product? (★★★)

#### Exercise: Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### Exercise: How to swap two rows of an array? (★★★)

#### Exercise: Read an image using openCV and tranpose it. What did you get exactly? Was the image rotated? Moved? Reflected with respect to an axis? (★★★)

#### Exercise: Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### Exercise: How to find the most frequent value in an array? (★★★)

#### Exercise: How to get the n largest values of an array (★★★)

#### Exercise: Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### Exercise: Given a two dimensional array, how to extract unique rows? (★★★)

#### Exercise: Can you have arrray of strings? can you mix different data types in the same array? Can you operate (add, sub, mult) arrays with different data types? (★★★)